# Generated by Django 4.2.30 on 2026-04-16 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_saved', models.DecimalField(decimal_places=2, max_digits=12)),
                ('necessity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('surplus_deficit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
