# Generated by Django 4.2.30 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_add_balance_history'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='savings.savingsgoal')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_contributions', to='banking.bankaccount')),
            ],
        ),
    ]
