# Generated by Django 4.2.30 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_autosaverule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(choices=[(25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')])),
                ('reached_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='savings.savingsgoal')),
            ],
            options={
                'ordering': ['percentage'],
                'unique_together': {('goal', 'percentage')},
            },
        ),
    ]
