# Generated by Django 4.2.30 on 2026-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_savingsmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingscontribution',
            name='transaction_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal')], default='contribution', max_length=12),
        ),
    ]
