# Generated by Django 4.2.30 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='recommendations_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
