# Generated by Django 4.2.30 on 2026-04-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_reason', models.CharField(choices=[('transaction', 'Transaction'), ('manual_update', 'Manual Update'), ('transfer', 'Transfer'), ('savings_contribution', 'Savings Contribution'), ('recurring', 'Recurring'), ('import', 'Import')], max_length=25)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='banking.bankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
