# Generated by Django 4.2.30 on 2026-04-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_recurringtransaction_subscription_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'bucket'], name='transaction_user_id_7cd3de_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account'], name='transaction_user_id_295b1e_idx'),
        ),
    ]
